spring.application.name=hadoop_back_end
server.port=8080
server.tomcat.threads.max=20
server.tomcat.threads.min-spare=2

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

management.endpoints.web.exposure.include=health,info,metrics

app.top-n=20
app.max-log-lines-memory=500
app.sse-timeout-ms=1800000
app.job-ttl-minutes=180